### ISSUE TITLE
Error owner solve this

### ISSUE THREAD

**Issue by amith598** [mayurkadampro/YouTube-SubBot#10]
python subbot.py
Traceback (most recent call last):
  File "/storage/emulated/0/Download/YouTube-SubBot/Part 1/YouTube-SubBot/Part 2/subbot.py", line 3, in <module>
    import pyautogui # its use for keyboard inputs.
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/data/data/com.termux/files/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

**Comment by amith598** [comment]
Slove

**Comment by Likhithsai2580** [comment]
I think your using mobile it will work on only windows
