### ISSUE TITLE
Traceback (most recent call last):   File "subbot.py", line 2, in <module>     from webbot import Browser ModuleNotFoundError: No module named 'webbot'

### ISSUE THREAD

**Issue by adamsetiaji** [mayurkadampro/YouTube-SubBot#3]

**Comment by amith598** [comment]
pip install webbot

**Comment by edcarSky** [comment]
NOT WORKING, PLS ADVISE

D:\Downloads\Youtube-Viewers\TEST\YouTube-SubBot-master>pip install webbot
Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\python-3.8\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

**Comment by Likhithsai2580** [comment]
reinstall python including pip

**Comment by edcarSky** [comment]
please help 

======== RESTART: C:\Python36\YouTube-SubBot-master\Part 2\subbot.py ========
Traceback (most recent call last):
  File "C:\Python36\YouTube-SubBot-master\Part 2\subbot.py", line 4, in <module>
    import win32console,win32gui
ModuleNotFoundError: No module named 'win32console'
>>>

**Comment by LuukieLucas** [comment]
pip install win32console

if u cant read python go ask me im only 11 u dumb fuck
